os: linux
language: generic
sudo: required
dist: xenial
env:
  - SWIFT_VERSION=5.0
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
addons:
  apt:
    packages:
      - oracle-java8-installer
script:
  - swift test
